apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: jwilder/whoami:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    app: bar
    service: bar
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: bar
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bar-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "bar.svc"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bar
spec:
  hosts:
  - "*"
  gateways:
  - bar-gateway
  http:
  - match:
    - uri:
        prefix: /
      authority:
        exact: bar.svc
    route:
    - destination:
        host: bar
        port:
          number: 8000
